### ISSUE TITLE
Error on documentation

### ISSUE THREAD

**Issue by Luan1Schons** [eternalodball/inscreate#1] opened 2022-02-19 19:59 UTC
Please help the url not working:
Usage
Go to https://rapidapi.com/zenno.dmv/api/temporary-mail-afeg-ru/pricing
Chose the free plan and get an api for free

**Comment by eternalodball** [comment] 2022-02-20 07:22
go to https://afeg.ru/
if you are getting 502 error then,
**the problem is on the website itself**
Sometimes these sites stops their service for maintenance . 
so please try again after some time . i will add more tempmail services soon ...

**Comment by eternalodball** [comment] 2022-02-23 07:46
I have changed the mail service and it's working now 
thanks for helping
you can close this issue or create a new

**Comment by eternalodball** [comment] 2022-02-23 10:47
> Please help the url not working: Usage Go to https://rapidapi.com/zenno.dmv/api/temporary-mail-afeg-ru/pricing Chose the free plan and get an api for free

**Closed as completed by eternalodball** 2022-02-23 10:47 UTC
